import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import * as c from '../controllers/doctor.controller.js';
const router = Router();
const publicLimit = rateLimit({ windowMs: 60000, limit: 120, standardHeaders: 'draft-8', legacyHeaders: false, message: { error: { code: 'RATE_LIMITED', message: 'Trop de demandes. Réessayez plus tard.' } } });
router.get('/specialties', publicLimit, c.specialties);
router.get('/doctors', publicLimit, c.search);
router.get('/doctors/:id', publicLimit, c.profile);
router.get('/doctors/:id/slots', publicLimit, c.slots);
export default router;
